config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users

  root to: 'pages#home'

  resources :users, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :users, only: [:index, :edit, :update, :show, :create, :destroy]
  end

  resources :users, only: [:index, :show] do
    resources :reviews, only: [:create, :index]
  end

  resources :users, only: [:index, :new, :create, :show] do
    resources :requests, only: [:index, :new, :create, :show]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :dances, only: [:index, :create, :show, :new, :edit]
  end

  resources :profiles, only: [:index, :show] do
    resources :meetings, only: [:create, :show]
  end

  resources :dances, only: [:index, :show, :new, :create] do
    resources :users, only: [:show]
  end

  resources :users, only: [:index, :show, :new, :create, :update] do
    resources :dances
  end

  resources :profiles, only: [:index, :new, :create, :show] do
    resources :requests, only: [:index, :new, :create, :show, :destroy]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :appointments, only: [:create, :show, :new]
  end

  resources :appointments, only: [:index, :show, :new, :create] do
    resources :users
  end

  resources :dances, only: [:show] do
    resources :appointments
  end

  resources :dances do
    resources :profiles, only: [:new, :create, :show, :destroy]
  end

  resource :appointments do
    resources :profiles
  end

  resources :appointments do
    resources :subscriptions, only: [:new, :create, :destroy]
  end

  resources :requests, only: [:index] do
    member do
      patch :accept
      patch :refuse
    end
  end
  namespace :api do
  resources :users, only: [:show, :update]
end
end

app/controllers/api/users_controller.rb
# app/controllers/api/users_controller.rb
module Api
  class UsersController < Api::BaseController
    include Devise::Controllers::Helpers
    before_action :authenticate_user
    before_action :set_user, only: [:show, :update]

    # GET /api/users/:id
    def show
      @user = User.find(params[:id])
      render json: user
    end

    # PUT /api/users/:id
    def update
      if @user.update(user_params)
        render json: @user
      else
        render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :first_name, :last_name, :age, :location, :city, :gender, :photo,
        :level, :xp, :coaching_status, :practice_a_week,
        :technique, :ambition, :social
      )
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
        image_url: helpers.asset_url('mapbox-marker-icon-green.svg')
      }
    end
  end

  def new
    @user = User.new(user_params)
    @user.save
  end

  def create
    # @user = current_user
    @user = User.new(user_params)
    @user.save
    #   redirect_to users_path(@users)
    # else
    #   render 'home'
    # end
    # @dance = Dance.new
    # session[:user_id] = user.id
    #   redirect_to registration_path
    # @user.save
    #   redirect_to profile_path
  end

  def show
    @profile = current_user
    @my_dances = []
    @profile.dances.each do |profile_dance|
    @dance = profile_dance.title
    @my_dances << @dance if !@my_dances.include?(@dance)
    end
    @users_of_this_dance = @users.where(dance_id: params[:id])
    @partners = @users_of_this_dance.each do |partner|
      partner.first_name
    end
  end

  # def new
  #   @dance = Dance.new
  #   @user = current_user
  #   @dances = Dance.all
  #   @dances.user = @user
  #   if dance.save
  #   redirect_to profile_path
  #   else
  #     render 'dances/show'
  #   end
  # end

  # def edit
  #   @user = current_user
  #   @dances = Dance.select('dances.*')
  #   #Select et s'ajoute dans la show du profil
  #   @my_dances = @dances.select(params[:id])
  #   # @user_dances = @dances.select(params[:id])
  # end

  # def edit
  #   @user = current_user
  #   @dances = Dance.select('dances.*')
  #   #Select et s'ajoute dans la show du profil
  #   @my_dances = @dances.select(params[:id])
  #   # @user_dances = @dances.select(params[:id])
  #   @user.save
  #     # redirect_to edit_profile_path(@dances)
  # end

  # def update
  #   @user = current_user
  #   @user_dances = Dance.select(params[:dance_id])
  #   @dance = Dance.find_by(id: params[:dance_id])
  #   @user.save
  # end

    def edit
    @profile = current_user
    # @dances = Dance.select('dances.*')
    #Select et s'ajoute dans la show du profil
    @my_dances = @dances.select(params[:id])
    @user_dances = @dances.select(params[:id])
    # redirect_to edit_profile_path(@dances)
  end

  def update
    @user = current_user
    # @user_dances = Dance.select(params[:dance_id])
    # @dance = Dance.find_by(id: params[:dance_id])
    @user.update(user_params)
      redirect_to profile_path
  end

  def destroy
    log_out
    redirect_to '/login'
  end

  private

  def set_user
    @user = User.find(params[:id])
    @users = User.all
  end

  def user_params
    params.require(:user).permit(:gender, :dances, :age, :location, :experience, :contact, :email, :encrypted_password, :password, :id, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:index, :create, :new, :show, :edit, :update, :destroy, :sign_out]
  # layout false
  def index
    @users = User.all
    @user = current_user
    @dances = Dance.all
    if params[:query].present? || params[:gender_query].present? || params[:name_query].present?
      @users  = User.where("location ILIKE ?", "%#{params[:query]}%")
                    .where("gender ILIKE ?", "%#{params[:gender_query]}%")
                    .where("first_name ILIKE ?", "%#{params[:name_query]}%")
    else
      @users =  User.all
    end

    @subscriptions = Subscription.where(user_id: :id)

    @dancers = @users.geocoded.map do |user|
      if user.gender == 'Gentleman'
        {
          lat: user.latitude,
          lng: user.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
          image_url: helpers.asset_url('dance-man.png'),
        }
      else
        {
          lat: user.latitude,
          lng: user.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
          image_url: helpers.asset_url('dance-woman.png'),
        }
      end
    end
    @mapmarkers = @markers.to_json

    @appointments = Appointment.all
    @events = @appointments.geocoded.map do |appointment|
      {
        lat: appointment.latitude,
        lng: appointment.longitude,
        infoWindow: render_to_string(partial: "info_window_event", locals: { appointment: appointment }),
        image_url: helpers.asset_url('show-icon.png'),
      }
    end
    @mapevents = @events.to_json

    @profiles = Profile.all

    # GEOLOCALISATION DES DANSEURS DE SALSA
    @partners_of_salsa = []
    @profiles.where(dance_id: 1).each do |salsa_partner|
      @partners_of_salsa << salsa_partner if !@partners_of_salsa.include? salsa_partner
    end
    @salsero_json = []
    @partners_of_salsa.each do |member|
    @salsero_json << member.user
    end
    @salsero_position_on_map = @salsero_json.map do |salserito|
      {
        lat: salserito.latitude,
        lng: salserito.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: salserito }),
        image_url: helpers.asset_url('marker.svg'),
      }
    end
    # GEOLOCALISATION DES DANSEURS DE MERENGUE
    # @partners_of_merengue = []
    # @profiles.where(dance_id: 2).each do |merengue_partner|
    #   @partners_of_merengue << merengue_partner if !@partners_of_merengue.include? merengue_partner
    # end
    # @merengue_json = []
    # @partners_of_merengue.each do |member|
    # @salsero_json << member.user
    # end
    # @merengue_position_on_map = @merengue_json.map do |merenguero|
    #   {
    #     lat: merenguero.latitude,
    #     lng: merenguero.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: merenguero }),
    #     image_url: helpers.asset_url('marker.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE BACHATA
    # @partners_of_bachata = []
    # @profiles.where(dance_id: 3).each do |bachata_partner|
    #   @partners_of_bachata << bachata_partner if !@partners_of_bachata.include? bachata_partner
    # end
    # @bachata_json = []
    # @partners_of_bachata.each do |member|
    # @bachata_json << member.user
    # end
    # @bachata_position_on_map = @bachata_json.map do |bachatero|
    #   {
    #     lat: bachatero.latitude,
    #     lng: bachatero.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: bachatero }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-green.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE KIZOMBA
    # @partners_of_kizomba = []
    # @profiles.where(dance_id: 4).each do |kizomba_partner|
    #   @partners_of_kizomba << kizomba_partner if !@partners_of_kizomba.include? kizomba_partner
    # end
    # @kizomba_json = []
    # @partners_of_kizomba.each do |member|
    # @kizomba_json << member.user
    # end
    # @kizomba_position_on_map = @kizomba_json.map do |kizombero|
    #   {
    #     lat: kizombero.latitude,
    #     lng: kizombero.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: kizombero }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-red.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE REGGAETON
    # @partners_of_reggaeton = []
    # @profiles.where(dance_id: 5).each do |reggaeton_partner|
    #   @partners_of_reggaeton << reggaeton_partner if !@partners_of_reggaeton.include? reggaeton_partner
    # end
    # @reggaeton_json = []
    # @partners_of_reggaeton.each do |member|
    # @reggaeton_json << member.user
    # end
    # @reggaeton_position_on_map = @reggaeton_json.map do |reggaetoner|
    #   {
    #     lat: reggaetoner.latitude,
    #     lng: reggaetoner.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: reggaetoner }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-gray.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE SAMBA
    # @partners_of_samba = []
    # @profiles.where(dance_id: 6).each do |samba_partner|
    #   @partners_of_samba << samba_partner if !@partners_of_samba.include? samba_partner
    # end
    # @samba_json = []
    # @partners_of_samba.each do |member|
    # @samba_json << member.user
    # end
    # @samba_position_on_map = @samba_json.map do |sambero|
    #   {
    #     lat: sambero.latitude,
    #     lng: sambero.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: sambero }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-gray.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE TANGO
    # @partners_of_tango = []
    # @profiles.where(dance_id: 7).each do |tango_partner|
    #   @partners_of_tango << tango_partner if !@partners_of_tango.include? tango_partner
    # end
    # @tango_json = []
    # @partners_of_tango.each do |member|
    # @tango_json << member.user
    # end
    # @tango_position_on_map = @tango_json.map do |tangueiro|
    #   {
    #     lat: tangueiro.latitude,
    #     lng: tangueiro.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: tangueiro }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-gray.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE FLAMENCO
    # @partners_of_flamenco = []
    # @profiles.where(dance_id: 8).each do |flamenco_partner|
    #   @partners_of_flamenco << flamenco_partner if !@partners_of_flamenco.include? flamenco_partner
    # end
    # @flamenco_json = []
    # @partners_of_flamenco.each do |member|
    # @flamenco_json << member.user
    # end
    # @flamenco_position_on_map = @flamenco_json.map do |flamenqueiro|
    #   {
    #     lat: flamenqueiro.latitude,
    #     lng: flamenqueiro.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: flamenqueiro }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-gray.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE JAZZ
    # @partners_of_jazz = []
    # @profiles.where(dance_id: 9).each do |jazz_partner|
    #   @partners_of_jazz << jazz_partner if !@partners_of_jazz.include? jazz_partner
    # end
    # @jazz_json = []
    # @partners_of_jazz.each do |member|
    # @jazz_json << member.user
    # end
    # @jazz_position_on_map = @jazz_json.map do |jazzeiro|
    #   {
    #     lat: jazzeiro.latitude,
    #     lng: jazzeiro.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: jazzeiro }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-gray.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE WEST COAST SWING
    # @partners_of_wcs = []
    # @profiles.where(dance_id: 10).each do |wcs_partner|
    #   @partners_of_wcs << wcs_partner if !@partners_of_wcs.include? wcs_partner
    # end
    # @wcs_json = []
    # @partners_of_wcs.each do |member|
    # @wcs_json << member.user
    # end
    # @wcs_position_on_map = @wcs_json.map do |swingueiro|
    #   {
    #     lat: swingueiro.latitude,
    #     lng: swingueiro.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: swingueiro }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-gray.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE BREAK DANCE
    # @partners_of_break = []
    # @profiles.where(dance_id: 12).each do |break_partner|
    #   @partners_of_break << break_partner if !@partners_of_break.include? break_partner
    # end
    # @break_json = []
    # @partners_of_break.each do |member|
    # @break_json << member.user
    # end
    # @break_position_on_map = @break_json.map do |breaker|
    #   {
    #     lat: breaker.latitude,
    #     lng: breaker.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: breaker }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-gray.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE SALSA PORTORICAINE
    # @partners_of_porto = []
    # @profiles.where(dance_id: 13).each do |porto_partner|
    #   @partners_of_porto << porto_partner if !@partners_of_porto.include? porto_partner
    # end
    # @porto_json = []
    # @partners_of_porto.each do |member|
    # @porto_json << member.user
    # end
    # @porto_position_on_map = @porto_json.map do |portoricano|
    #   {
    #     lat: portoricano.latitude,
    #     lng: portoricano.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { user: portoricano }),
    #     image_url: helpers.asset_url('mapbox-marker-icon-gray.svg'),
    #   }
    # end

    # # GEOLOCALISATION DES DANSEURS DE FOX TROT
    # @partners_of_foxtrot = []
    # @profiles.where(dance_id: 15).each do |foxtrot_partner|

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_info_window.html.erb
<div class="info-window-user">
  <h2><%= user.first_name %></h2>
  <%= cl_image_tag user.photo.key if user.photo.attached?  %>
  <h2><%= user.city %></h2>
  <h2><% user.profiles.each do |profile| %></h2>
  <h2><%= profile.dance.title %></h2>
  <% end %>
  <div class="title_text">
    <p><%= link_to "Contact" %></p>
  </div>
</div>

app/views/users/_info_window_event.html.erb
<div class="info-window-event">
  <h2><%= appointment.name %></h2>
  <%= cl_image_tag appointment.pic.key if appointment.pic.attached?  %>
  <h2><%= appointment.address %></h2>
  <div class="title_text">
    <p><%= link_to "Participer" %></p>
  </div>
</div>

app/views/users/_marker.html.erb
<img src= "https://res.cloudinary.com/hnnyhemvj/image/upload/v1720115309/mapbox-marker-icon-20px-yellow_d862lo.png">

app/views/users/edit.html.erb
<div class="container-edition px-6 py-8 bg-white rounded-xl shadow-md max-w-3xl mx-auto">
  <h2 class="text-2xl font-semibold mb-6">Modifier mon profil</h2>

  <%= simple_form_for(current_user, method: :put, html: { class: "space-y-6" }) do |f| %>
    <%= f.error_notification %>

    <!-- Photo -->
<!--     <div class="flex items-center space-x-4">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "w-12 h-12 rounded-full object-cover border" %>
      <% end %>
      <div>
        <%= f.label :photo, "Changer la photo", class: "block font-medium text-sm text-gray-700" %>
        <%= f.file_field :photo, class: "mt-1 text-sm" %>
      </div>
    </div> -->

    <!-- Informations de base -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <%= f.input :first_name, required: true, input_html: { value: current_user.first_name, class: "form-input" } %>
      <%= f.input :last_name, required: true, input_html: { value: current_user.last_name, class: "form-input" } %>
      <%= f.input :age, required: true, input_html: { placeholder: current_user.age, class: "form-input" } %>
      <%= f.input :location, required: true, input_html: { placeholder: current_user.location, class: "form-input" } %>
      <%= f.input :city, required: true, input_html: { placeholder: current_user.city, class: "form-input" } %>
    </div>

    <!-- Sélections -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <%= f.input :gender, collection: User::GENDER_TYPES, prompt: "Genre", label: "Genre", input_html: { class: "form-select" } %>
      <%= f.input :level, collection: User::LEVELS, prompt: "Niveau", label: "Niveau", input_html: { class: "form-select" } %>
      <%= f.input :xp, collection: User::XPS, prompt: "Expérience", label: "Expérience", input_html: { class: "form-select" } %>
      <%= f.input :coaching_status, collection: User::COACHING_STATUS, prompt: "Statut", label: "Coaching", input_html: { class: "form-select" } %>
      <%= f.input :practice_a_week, collection: User::PRACTICE_A_WEEK, prompt: "Heures / semaine", label: "Fréquence", input_html: { class: "form-select" } %>
      <%= f.input :technique, collection: User::TECHNIQUE, prompt: "Technique", label: "Technique", input_html: { class: "form-select" } %>
      <%= f.input :ambition, collection: User::AMBITION, prompt: "Ambition", label: "Ambition", input_html: { class: "form-select" } %>
      <%= f.input :social, collection: User::SOCIAL, prompt: "Social", label: "Activité sociale", input_html: { class: "form-select" } %>
    </div>

    <!-- Bouton -->
    <div class="pt-4">
      <%= f.button :submit, "Mettre à jour", class: "px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition" %>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="container-show-profile">
  <div class="container1">
      <!-- <div class ="container-map">
          <div id="resultats"
          data-my-appointments="<%= @appointments_selected.to_json %>">
          </div>
          <div id="map"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
        <div id='map' style='width: 100%; height: 100%;'></div>
      </div> -->
    <div class="my_profile">
        <div class="dance-query">
          <div class="query">
            <%= form_tag dances_path, method: :get do %>
            <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Cherche ta danse" %>
          </div>
          <div class="button-OK">
            <%= submit_tag "Search", class: "btn-primary" %>
          </div>
          <% end %>
        </div>

          <div class="banner-profile">
            <div class="image-profile">
              <%= cl_image_tag current_user.photo.key if current_user.photo.attached? %>
            </div>
            <div class="my-informations">
              <h5><%= current_user.first_name %> <%= current_user.last_name %></h5>
              <a><%= current_user.gender %></a><br>
              <a><%= current_user.age %> years old</a><br>
              <a><%= current_user.location %></a><br>
              <a><%= current_user.experience %> years experience</a><br>
            </div>
            <div class ="menu-block">
              <h5>
                <%= pluralize current_user.reviews.size, "review" %><br>
                <%= link_to "See all reviews", user_reviews_path(current_user) %><br>
                <%= link_to "See all requests", user_requests_path(current_user) %><br>
                <%= link_to "Edit my profile", edit_user_path(current_user) %><br>
              </h5>
            </div>


  </div>
      <div class="container-appointments-profile">
        <div class="button-block">
          <div class="titres-cadre">
            <div class="titres">
              <p>Mes profils danses <%= link_to "+", dances_path %></p>
            </div>
              <% if @user.profiles.blank? %>
            <div class="infos-card" >
              <div class="ecriture">
                <%= link_to "Sélectionnez vos danses en cliquant ici", dances_path %><br></a>
              </div>
            </div>
              <% else %>
            <div class="infos-card" >
              <% @user.profiles.each do |pro_file| %>
            <div class="carte-profil" >
              <%= link_to pro_file.dance.title, profile_path(pro_file) %>
              <%= button_to 'Destroy', profile_path(pro_file), method: :delete %>
              <%= link_to "Edit", edit_profile_path(pro_file) %>
              <i class="bi bi-pen"></i>
              <ul>
                <a><%= pro_file.investissement %></a>
                <a><%= pro_file.niveau %></a>
                <a><%= pro_file.training_per_week %> hours/week</a>
              </ul>
            </div>
                <% end %>
              </div>
            <% end %>
        </div>

        <div class="titres-cadre" style="background-color: #FFFF; color:black;">
          <div class="titres"><p>Membres</p></div>
            <div class="infos-card-2" style="padding:10px;">
              <% @users.each do |user| %>
              <div class="profile-unique" style="margin-right:auto; margin-left:auto;">
                <%= cl_image_tag user.photo.key if user.photo.attached? %><br>
                <a><%= link_to user.first_name, user_profiles_path(user)  %></a>
              </div>
            <% end %>
            </div>
        </div>

        <div class="titres-cadre" style="background-color: #FFFF; color:black;">
          <div class="titres"><p>Vous avez effectué ces demandes</p>
            <div class="infos-card">
              <% current_user.requests.each do |r| %>
              <%= r.profile.dance.title %> with <%= r.profile.user.first_name %><br>
              <% end %>
            </div>
          </div>
        </div>

        <div class="titres-cadre" style="background-color: #FFFF; color:black;">
          <div class="titres">
            <p>Vous avez reçu ces demandes</p>
              <div class="infos-card">
                <% @dancing_partners.each do |dancing_partner| %>
                <%= dancing_partner.user.first_name %> wants to dance <%= dancing_partner.profile.dance.title %><br>
                <%= link_to "Voir la demande", requests_path(dancing_partner) %><br>
              <% end %>
              </div>
          </div>
        </div>

          <div class="my-event" style="display:grid;
                                        grid-template-columns: 1fr 1fr;
                                        grid-gap: 10px;
                                        grid-auto-rows: minmax(5px, auto);">
            <% current_user.appointments.each do |user_events| %>
              <div class="card-my-event">
                <div class="one-event">
                  <%= image_tag user_events.pic if user_events.pic.attached? %>
                  <a><%= user_events.name %></a>
                  <a><%= user_events.start_on %></a>
                  <a><%= user_events.address %></a>
                  <a><%= link_to "Voir sur la carte", appointments_path %></a>
                </div>
              </div>
            <% end %>

          </div>
          <div class="my-event" style="display:grid;
                                        grid-template-columns: 1fr 1fr;
                                        grid-gap: 10px;
                                        grid-auto-rows: minmax(5px, auto);">
            <% current_user.subscriptions.each do |subscription| %>
              <div class="card-my-event">
                <div class="one-event">
                  <%= image_tag subscription.appointment.pic if subscription.appointment.pic.attached? %>
                  <a><%= subscription.appointment.name %></a>
                  <a><%= subscription.appointment.start_on %></a>
                  <a><%= subscription.appointment.address %></a>
                  <a><%= link_to "Voir sur la carte", appointments_path %></a>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<!--       <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoiYW50bWFuNDMiLCJhIjoiY2x3eHk0aWF1MWY2bzJucjFodnEwemRwayJ9.O7VyKyjd4FebVbtQPuGj7g';
        var map = new mapboxgl.Map({
          container: 'map',
          style: 'mapbox://styles/mapbox/streets-v11'
        });
      </script> -->
    </div>
  </div>