config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users

  root to: 'pages#home'

  resources :users, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :users, only: [:index, :edit, :update, :show, :create, :destroy]
  end

  resources :users, only: [:index, :show] do
    resources :reviews, only: [:create, :index]
  end

  resources :users, only: [:index, :new, :create, :show] do
    resources :requests, only: [:index, :new, :create, :show]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :dances, only: [:index, :create, :show, :new, :edit]
  end

  resources :profiles, only: [:index, :show] do
    resources :meetings, only: [:create, :show]
  end

  resources :dances, only: [:index, :show, :new, :create] do
    resources :users, only: [:show]
  end

  resources :users, only: [:index, :show, :new, :create, :update] do
    resources :dances
  end

  resources :profiles, only: [:index, :new, :create, :show] do
    resources :requests, only: [:index, :new, :create, :show, :destroy]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :appointments, only: [:create, :show, :new]
  end

  resources :appointments, only: [:index, :show, :new, :create] do
    resources :users
  end

  resources :dances, only: [:show] do
    resources :appointments
  end

  resources :dances do
    resources :profiles, only: [:new, :create, :show, :destroy]
  end

  resource :appointments do
    resources :profiles
  end

  resources :appointments do
    resources :subscriptions, only: [:new, :create, :destroy]
  end

  resources :requests, only: [:index] do
    member do
      patch :accept
      patch :refuse
    end
  end
  namespace :api do
  resources :users, only: [:show, :update]
end
end

app/views/shared/_footer.html.erb
<div class="footer-container">
  <a>Performed By</a><br>
  <a>Lite Services </a>
  <a>©2021</a>
</div>

app/views/shared/_navbar.html.erb
<div class="contenu-body">
  <% if current_user == nil %>
  <div class="responsive-container">
    <div class="title-profile">
      <h1><%= link_to "Dancing Partners", root_path %></h1>
      <p><%= link_to "The First WorldWide Dancers Community", root_path %></p>
      <div class="section-navbar-logout">

          <div class="column-2">
            <a class="link"><%= link_to "Connexion", new_user_session_path %></a>
          </div>
          <div class="column-2">
            <a class="link"><%= link_to "Communauté", users_path %></a>
          </div>
          <div class="column-2">
            <a class="link"><%= link_to "Danses", dances_path %></a>
          </div>
          <div class="column-2">
            <a class="link"><%= link_to "Agenda", appointments_path %></a>
          </div>

      </div>
    </div>
  </div>
      <% else %>
  <div class="responsive-container-2">
    <div class="title-profile">
      <div class="navbar-sup" style="display:flex;" >
        <div class="titres-navbar" >
          <h1><%= link_to "Dancing Partners", root_path %></h1>
          <p><%= link_to "The First WorldWide Dancers Community", root_path %></p>
        </div>
        <div class="current-user-avatar-2" >
          <div class="picProfile">
            <%= cl_image_tag current_user.photo.key if current_user.photo.attached? %><br>
          </div>
          <div class="nameProfile">
            <a><%= current_user.first_name %></a>
          </div>
        </div>
      </div>
      <div class="section-navbar-login">

          <div class="column-2">
            <a class="link"><%= link_to "Profil", user_path(current_user) %></a>
          </div>
          <div class="column-2">
            <a class="link"><%= link_to "Communauté", users_path %></a>
          </div>
          <div class="column-2">
            <a class="link"><%= link_to "Danses", dances_path %></a>
          </div>
          <div class="column-2">
            <a class="link"><%= link_to "Evénements", appointments_path %></a>
          </div>
          <div class="column-2">
            <a class="link"><%= link_to "Edit", edit_user_path(current_user) %></a>
          </div>
          <div class="column-2">
            <a class="link"><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></a>
          </div>

      </div>
    </div>
  </div>
    <% end %>
</div>