config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  devise_for :users

  root to: 'pages#home'

  resources :users, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :users, only: [:index, :edit, :update, :show, :create, :destroy]
  end

  resources :users, only: [:index, :show] do
    resources :reviews, only: [:create, :index]
  end

  resources :users, only: [:index, :new, :create, :show] do
    resources :requests, only: [:index, :new, :create, :show]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :dances, only: [:index, :create, :show, :new, :edit]
  end

  resources :profiles, only: [:index, :show] do
    resources :meetings, only: [:create, :show]
  end

  resources :dances, only: [:index, :show, :new, :create] do
    resources :users, only: [:show]
  end

  resources :users, only: [:index, :show, :new, :create, :update] do
    resources :dances
  end

  resources :profiles, only: [:index, :new, :create, :show] do
    resources :requests, only: [:index, :new, :create, :show, :destroy]
  end

  resources :profiles, only: [:index, :edit, :update, :show, :create, :destroy] do
    resources :appointments, only: [:create, :show, :new]
  end

  resources :appointments, only: [:index, :show, :new, :create] do
    resources :users
  end

  resources :dances, only: [:show] do
    resources :appointments
  end

  resources :dances do
    resources :profiles, only: [:new, :create, :show, :destroy]
  end

  resource :appointments do
    resources :profiles
  end

  resources :appointments do
    resources :subscriptions, only: [:new, :create, :destroy]
  end

  resources :requests, only: [:index] do
    member do
      patch :accept
      patch :refuse
    end
  end
  namespace :api do
  resources :users, only: [:show, :update]
end
end

app/models/dance.rb
class Dance < ApplicationRecord
<<<<<<< HEAD
# belongs_to :user
# belongs_to :partner
has_many :partners
has_many :users
has_many :appointments

validates :title, presence: true
=======
  has_many :appointments
  has_many :users, through: :appointments
  has_many :profiles
  # belongs_to :users
  validates :title, presence: true
  has_one_attached :photo
>>>>>>> 87642039e64e140e485442c7f940c8ace596168f
end

app/controllers/dances_controller.rb
class DancesController < ApplicationController
before_action :set_dance, only: [:show]

def index
  if params[:query].present?
    @dances = Dance.where("lower(title) LIKE ?", "%#{params[:query].downcase}%")
  else
    @dances = Dance.all
  end
  @dance = @dances.each do |dance|
    puts dance.title
  end
  @style = @dance.find(params[:id])
  @dancer = @style.each do |yd|
    puts yd
  end
  @my_selected_dances = []
end

def new
  @dance = Dance.new
  @dance.save
end

def create
  @user = current_user
  @dance = Dance.new(dance_params)
  @dance.user = @user
  if @dance.save
    redirect_to dances_path(@dance)
  else
    render 'profile/show'
  end
end

def show
  # @user = current_user
  @dances = Dance.all
  # @dance = Dance.find(params[:id])
  @style = @dance.title
  @profiles = Profile.all
  @partners_of_this_dance = []
  @profiles.where(dance_id: params[:id]).each do |partner|
    @partners_of_this_dance << partner if !@partners_of_this_dance.include? partner
  end
  @my_new_dances = []
    @dances.select do |my_moving|
      @my_new_dances << my_moving if my_moving
    end
  # afficher sous une liste index/card, tous les evenements de cette danse
  @appointments = Appointment.all
  @appointments_on_map = @appointments.where(dance_id: params[:id])
  @markers = @appointments_on_map.geocoded.map do |appointment_on_map|
      {
        lat: appointment_on_map.latitude,
        lng: appointment_on_map.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { appointment_on_map: appointment_on_map }),
        image_url: helpers.asset_url('mapbox-marker-icon-red.svg')
      }
    end
  @users = User.all
  @event_managers = @dance.users
  @users_of_this_dance = Profile.where(dance_id: params[:id])
end

  def update
    @dance = Dance.find(params[:id])
    @dance.update(dance_params)
    @dance.save
  end

  def destroy
    @dance = Dance.find(params[:id])
    @user = @dance.user
    @dance.destroy
    redirect_to profile_path(@user)
  end

  private

  def set_dance
    @dance = Dance.find(params[:id])
  end

  def dance_params
    params.require(:dance).permit(:title, :user_id, :photo)
  end
end

app/helpers/dances_helper.rb
module DancesHelper
  def dances_for_select
    Dance.all.collect { |m| [m.title, m.id] }
  end
end

app/views/dances/_dance_card.html.erb
<div class="card-plant">
  <%= dance.name %>
  <%= link_to "+", profile_path(@dances), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
</div>

app/views/dances/_form.html.erb
<%= simple_form_for(dance) do |f| %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :user %>
  <%= f.submit %>
<% end %>

<%= form_for(@dance) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dances/_info_window.html.erb
<h2><%= appointment_on_map.name %></h2>
<p><%= appointment_on_map.address %></p>

app/views/dances/index.html.erb
<div class="container-card-profile">
  <div class="container-dances">
    <div class="search1">
      <div class="enter-your-dance">
        <%= form_tag dances_path, method: :get do %>
        <%= text_field_tag :query,
          params[:dance],
          class: "form-control",
          placeholder: "Nom de la danse"
        %>
      </div>
      <div class="validate-your-dance">
        <%= submit_tag "Search", class: "b-prima-1" %>
      </div>
      <% end %>
    </div>
      <p>Dancing Partners has found <%=  pluralize @style.count, "dance" %></p>
        <div class="container-card_dances">
      <% @dances.each do |dance| %>
      <div class="dance_card">
        <h3><%= link_to dance.title, dance_path(dance) %></h3>
        <div class="image-dance">
        <%= cl_image_tag dance.photo.key if dance.photo.attached? %>
      </div>
        <%= pluralize dance.profiles.count, "dancer" %><br>
        <%= pluralize dance.appointments.count, "événement" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dances/new.html.erb
<div class="pt-30 container">
  <h1 class="text-center"> Add your Dance</h1>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@dance) do |f| %>
        <div class="form-inputs">
          <%= f.input :title %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dances/show.html.erb
<div class="container-card-profile">
  <div class="container-3">
    <div class="container-one-dance">
      <div class="profile-dance-card2">
        <h1>Grille de la communauté</h1><h2 style="text-decoration:none;"><%= link_to @style, dance_path(@dance) %></h2>
        All App Users: <a><%= @users.count %> </a><br>
        Total Dances Profiles: <a><%= @profiles.count %> </a><br>
        Total Community <a style="font-weight:bold;"><%= @style %> Dancers</a>: <%= @partners_of_this_dance.count %><br>
        <div class="list-community-dancers">
        <% @partners_of_this_dance.each do |member| %>
          <div class="image-dancers">
            <%= image_tag member.user.photo %><br>
          </div>
        <% end %>
        <br>
        </div>
          <p><%= pluralize @appointments_on_map.count, "organisateur" %></p>
          <div class="list-community-dancers">
          <% @event_managers.each do |manager| %>
            <div class="image-dancers">
              <%= manager.first_name %>
              <%= image_tag manager.photo %>
            </div>
          <% end %>
        </div>
        <div class="add-dance">
          <div class="button"><a><%= link_to "Ajouter à ma sélection", new_dance_profile_path(@dance) %></a></div>
          <div class="button"><a><%= link_to "Choisir comme danse favorite", profile_path(@dance), method: :put %></a></div>
          <div class="button"><a><%= link_to "Créer", new_appointment_path(@dance.id), method: :get, class:"btn btn-primary", id: "dance" %></a></div>
        </div>
      </div>
    </div>
    <div class="events-list">
      <% @appointments_on_map.each do |an_event| %>
        <div class="card-event-of-dance">
            <%= image_tag an_event.pic %>
          <div class="carte-details">
            <a><%= an_event.name %></a><br>
            <a><%= an_event.address %></a>
            <%= image_tag an_event.user.photo %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<h2 class="text-xl font-bold mb-4">Danseurs de <%= @style %></h2>
<p class="mb-2 text-sm text-gray-600">
  Total : <strong><%= @partners_of_this_dance.count %></strong>
</p>

<div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4 mb-6">
  <% @partners_of_this_dance.each do |member| %>
    <div class="bg-white rounded-lg shadow p-3 flex flex-col items-center text-center hover:shadow-md transition">
      <% if member.user.photo.attached? %>
        <%= image_tag member.user.photo, class: "w-2 h-2 rounded-full object-cover border mb-2" %>
      <% else %>
        <div class="w-20 h-20 rounded-full bg-gray-200 mb-2 flex items-center justify-center text-sm text-gray-500">No Photo</div>
      <% end %>
      <p class="font-medium text-sm"><%= member.user.first_name %></p>
      <p class="text-xs text-gray-500"><%= member.user.city %></p>
    </div>
  <% end %>
</div>